authors:
  sandipan:
    name: Sandipan Haldar
    description: Applied AI Consultant
    # avatar: https://imgur.com/a/7U5MeKP
    avatar: blog/avatar.jpeg
    # avatar: https://pbs.twimg.com/profile_images/1838778744468836353/utYfioiO_400x400.jpg
    url: https://twitter.com/intent/follow?screen_name=HaldarHq